"use client";
import NavBar from "@/components/NavBar";
import "./globals.css";
import Image from "next/image";
import Footer from "@/components/Footer";
import NavListItem from "@/components/ui/NavListItem";
import { useState } from "react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showModal, setShowModal] = useState(false);

  const handleshowModal = () => {
    setShowModal((prev) => !prev);
    if (!showModal) {
      document.body.classList.add("no-scroll");
    } else {
      document.body.classList.remove("no-scroll");
    }
  };

  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <NavBar handleShowModal={handleshowModal} showModal={showModal} />
        {showModal && (
          <div className="w-full mt-[4.9rem] fixed top-0 z-50 left-0 h-[100vh] bg-gradient-to-b from-[#191c2e]">
            <div className="flex justify-center w-full pt-10">
              <ul className="text-center rounded-lg opacity-100 w-72 p-11 bg-slate-900">
                <NavListItem href="about-us">About Us</NavListItem>
                <NavListItem href="contact">Contact</NavListItem>
                <NavListItem href="Blog">Blog</NavListItem>
                <NavListItem href="careeers">Careers</NavListItem>
                <NavListItem href="Support">Support</NavListItem>
              </ul>
            </div>
          </div>
        )}
        {children}
        <Footer />
      </body>
    </html>
  );
}
